os:
  - linux
  - osx
  - windows

branches: 
  only:
    - master
    - develop
    - /v*/

sudo: false

language: go

go:
  - 1.11.x

git:
  depth: 1

script:
  - go get golang.org/x/sys/windows/registry

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then GOARCH=amd64 GOOS=darwin go build -o ${TRAVIS_BUILD_DIR}/bin/preview-mac ./src/preview/main.go ; fi  
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x ${TRAVIS_BUILD_DIR}/bin/preview-mac ; fi  

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then GOARCH=amd64 GOOS=linux go build -o ${TRAVIS_BUILD_DIR}/bin/preview-linux ./src/preview/main.go ; fi  
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then chmod +x ${TRAVIS_BUILD_DIR}/bin/preview-linux ; fi  

  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then go build -o ${TRAVIS_BUILD_DIR}/bin/preview-windows.exe .\\src\\preview\\main.go ; fi

  - ls
  - ls bin

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: 
  - ${TRAVIS_BUILD_DIR}/bin/preview-linux
  - ${TRAVIS_BUILD_DIR}/bin/preview-mac
  - ${TRAVIS_BUILD_DIR}/bin/preview-windows.exe
  skip_cleanup: true
  draft: true
  overwrite: true
  on:
    tags: true