os: Visual Studio 2015

clone_folder: C:\gopath\src\github.com\ethereum\go-ethereum
clone_depth: 1
version: "{branch}.{build}"
environment:
  GOPATH: C:\gopath

platform:
  - x64

install:
  - go version

build_script:
  - ls
  - go build -o ./bin/preview-windows.exe .\\src\\preview\\main.go