os: Visual Studio 2015

clone_folder: C:\gopath\src\github.com\ethereum\go-ethereum
shallow_clone: false
version: "{branch}.{build}"
environment:
  GOPATH: C:\gopath

platform:
  - x64

install:
  - go version

build_script:
  - go build -o ./bin/preview-windows.exe .\\src\\preview\\main.go
  - ls

deploy:
  - provider: GitHub
    release: $APPVEYOR_REPO_TAG_NAME
    artifact:  preview
    draft: true
    prerelease: true
    auth_token:
        secure: gp3B0d647liCCrSzh7SBcTGAA5d+QoZtC9pTnO+fXYjhp2Zi95JcAvFbLe5kIEce
    on:
     appveyor_repo_tag: false

artifacts:
  - path: ./bin/preview-windows.exe
    name: preview
